In [1]:
import pickle
import pandas as pd

In [2]:
## load scraped reviews data
reviews = pickle.load(open("../data/hotel_reviews_final.pkl", "rb"))
reviews = reviews.rename(columns={'url': 'link'})
print(reviews.shape)
reviews.head()

(76536, 12)

index,name,room_type,nights_stayed,month_stayed,occupant_type,from_country,review_score,date_reviewed,short_review,positive_review,negative_review,link
0,Gene,,2 nights,January 2020,Couple,Philippines,10,January 2020,Exceptional,I love the pool coz I was so lucky to swim alo...,nothing..,https://www.booking.com/hotel/ph/meranti.html?...
1,Sheila,Executive Twin Room,1 night,November 2022,Family,Philippines,7.0,November 2022,"Overall, we love the place, the staff and all...",We like that all the staff are very friendly. ...,I'm unhappy that we only got plated breakfast ...,https://www.booking.com/hotel/ph/meranti.html?...
2,Greggy,Executive Twin Room,1 night,October 2022,Solo traveler,Philippines,8.0,October 2022,Nice,Simple and comfortable,the location,https://www.booking.com/hotel/ph/meranti.html?...
3,Tay,Executive Twin Room,2 nights,October 2022,Family,Cambodia,7.0,October 2022,Good,Staff,Lack of service facilties not even coffee in r...,https://www.booking.com/hotel/ph/meranti.html?...
4,Joseph,Executive Twin Room,1 night,July 2022,Family,Philippines,9.0,July 2022,"Overall, it was a very comfortable experience...",The room was very clean and everything we need...,,https://www.booking.com/hotel/ph/meranti.html?...

In [3]:
## check info
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 76536 entries, 0 to 78298
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             76536 non-null  object
 1   room_type        76536 non-null  object
 2   nights_stayed    76536 non-null  object
 3   month_stayed     76536 non-null  object
 4   occupant_type    76536 non-null  object
 5   from_country     76536 non-null  object
 6   review_score     76536 non-null  object
 7   date_reviewed    76536 non-null  object
 8   short_review     76536 non-null  object
 9   positive_review  76536 non-null  object
 10  negative_review  76536 non-null  object
 11  link             76536 non-null  object
dtypes: object(12)
memory usage: 7.6+ MB

In [4]:
## load hotel info
hotels = pickle.load(open("../data/hotel_info_final.pkl", "rb"))
print(hotels.shape)
hotels.head()

(307, 71)

,hotel_name_,stars,location,review_rating,description,main_facilities,total_reviews,sub_ratings,sub_ratings_categories,sub_ratings_dict,...,hairdryer,slippers,key access,accessible parking,facilities for disabled guests,wardrobe or closet,clothes rack,socket near the bed,bar,ironing service
0,RedDoorz near East Avenue Medical Center,2,"90 Matatag Street, Quezon City, 1100 Manila, P...",6.0,RedDoorz near East Avenue Medical Center featu...,"[Non Smoking Rooms, Free WiFi Internet Access ...",88,"[6.9, 6.3, 6.5, 6.5, 7.0, 7.8, 6.3]","[Staff, Facilities, Cleanliness, Comfort, Valu...","{'Staff': '6.9', 'Facilities': '6.3', 'Cleanli...",...,0,0,1,0,0,0,0,0,0,0
1,Skylab Guesthouse,2,"213B, Aldrin Street, Moonwalk Village 1, Parañ...",8.0,You're eligible for a Genius discount at Skyla...,"[Non Smoking Rooms, Spa & Wellness Centre, Fre...",79,"[8.8, 7.8, 8.3, 8.4, 8.4, 8.1, 7.5]","[Staff, Facilities, Cleanliness, Comfort, Valu...","{'Staff': '8.8', 'Facilities': '7.8', 'Cleanli...",...,1,1,1,0,0,0,0,1,0,1
2,The Excelsior Hotel Las Piñas,4,"1345 Alabang–Zapote Road, Las Pinas, 1750 Mani...",7.3,"Located in Manila, 12.2 km from Mall of Asia A...","[Swimming pool, Airport Shuttle, Non Smoking R...",6,"[7.9, 8.3, 7.9, 8.8, 7.9, 7.9, 7.9]","[Staff, Facilities, Cleanliness, Comfort, Valu...","{'Staff': '7.9', 'Facilities': '8.3', 'Cleanli...",...,1,1,0,1,0,1,1,1,1,0
3,Rothman Hotel,3,"1633 M. Adriatico St., Malate, 1004 Manila, Ph...",7.8,Rothman Hotel is located in the district of Ma...,"[Non Smoking Rooms, Room-service, Free Parking...",45,"[8.3, 7.6, 8.0, 7.8, 7.8, 8.7, 8.8]","[Staff, Facilities, Cleanliness, Comfort, Valu...","{'Staff': '8.3', 'Facilities': '7.6', 'Cleanli...",...,0,0,0,0,1,0,0,0,1,1
4,OYO 772 Remedios Apartment,3,"909, Remedios St, Manila Malate Manila, 1004 M...",6.8,You're eligible for a Genius discount at OYO 7...,"[Non Smoking Rooms, Free WiFi Internet Access ...",113,"[7.5, 6.5, 6.9, 6.9, 7.0, 7.7, 8.8]","[Staff, Facilities, Cleanliness, Comfort, Valu...","{'Staff': '7.5', 'Facilities': '6.5', 'Cleanli...",...,0,0,1,0,0,0,0,0,0,0

In [5]:
hotels.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 307 entries, 0 to 306
Data columns (total 71 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   hotel_name_                          307 non-null    object
 1   stars                                307 non-null    int64
 2   location                             307 non-null    object
 3   review_rating                        307 non-null    object
 4   description                          307 non-null    object
 5   main_facilities                      307 non-null    object
 6   total_reviews                        307 non-null    object
 7   sub_ratings                          307 non-null    object
 8   sub_ratings_categories               307 non-null    object
 9   sub_ratings_dict                     307 non-null    object
 10  hotel_surroundings                   307 non-null    object
 11  hotel_surroundings_distance          307 non-null    object
 12  surroundings_dict                    307 non-null    object
 13  room_type                            307 non-null    object
 14  price_list                           307 non-null    object
 15  cheapest_price                       307 non-null    float64
 16  facilities_groups                    307 non-null    object
 17  all_facilities                       307 non-null    object
 18  link                                 307 non-null    object
 19  room_price_dict                      307 non-null    object
 20  facilities_count                     307 non-null    int64
 21  air conditioning                     307 non-null    int64
 22  non-smoking rooms                    307 non-null    int64
 23  fire extinguishers                   307 non-null    int64
 24  cctv in common areas                 307 non-null    int64
 25  private bathroom                     307 non-null    int64
 26  smoke alarms                         307 non-null    int64
 27  toilet                               307 non-null    int64
 28  tv                                   307 non-null    int64
 29  24-hour security                     307 non-null    int64
 30  towels                               307 non-null    int64
 31  free toiletries                      307 non-null    int64
 32  24-hour front desk                   307 non-null    int64
 33  shower                               307 non-null    int64
 34  toilet paper                         307 non-null    int64
 35  airport shuttle                      307 non-null    int64
 36  elevator                             307 non-null    int64
 37  linens                               307 non-null    int64
 38  security alarm                       307 non-null    int64
 39  flat-screen tv                       307 non-null    int64
 40  daily housekeeping                   307 non-null    int64
 41  cctv outside property                307 non-null    int64
 42  room service                         307 non-null    int64
 43  designated smoking area              307 non-null    int64
 44  safe                                 307 non-null    int64
 45  desk                                 307 non-null    int64
 46  bidet                                307 non-null    int64
 47  smoke-free property                  307 non-null    int64
 48  baggage storage                      307 non-null    int64
 49  cable channels                       307 non-null    int64
 50  telephone                            307 non-null    int64
 51  restaurant                           307 non-null    int64
 52  key card access                      307 non-null    int64
 53  electric kettle                      307 non-null    int64
 54  meeting/banquet facilities           307 non-null    int64
 55  laundry                              307 non-null    int64
 56  fax/photocopying                     307 non-null    int64
 57  upper floors accessible by elevator  307 non-null    int64
 58  family rooms                         307 non-null    int64
 59  wake-up service                      307 non-null    int64
 60  concierge                            307 non-null    int64
 61  hairdryer                            307 non-null    int64
 62  slippers                             307 non-null    int64
 63  key access                           307 non-null    int64
 64  accessible parking                   307 non-null    int64
 65  facilities for disabled guests       307 non-null    int64
 66  wardrobe or closet                   307 non-null    int64
 67  clothes rack                         307 non-null    int64
 68  socket near the bed                  307 non-null    int64
 69  bar                                  307 non-null    int64
 70  ironing service                      307 non-null    int64
dtypes: float64(1), int64(52), object(18)
memory usage: 172.7+ KB

In [6]:
## merge the two tables
all = hotels.merge(reviews, on = 'link', how = 'outer')
print(all.shape)
all.info()

(76536, 82)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 76536 entries, 0 to 76535
Data columns (total 82 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   hotel_name_                          76536 non-null  object
 1   stars                                76536 non-null  int64
 2   location                             76536 non-null  object
 3   review_rating                        76536 non-null  object
 4   description                          76536 non-null  object
 5   main_facilities                      76536 non-null  object
 6   total_reviews                        76536 non-null  object
 7   sub_ratings                          76536 non-null  object
 8   sub_ratings_categories               76536 non-null  object
 9   sub_ratings_dict                     76536 non-null  object
 10  hotel_surroundings                   76536 non-null  object
 11  hotel_surroundings_distance          76536 non-null  object
 12  surroundings_dict                    76536 non-null  object
 13  room_type_x                          76536 non-null  object
 14  price_list                           76536 non-null  object
 15  cheapest_price                       76536 non-null  float64
 16  facilities_groups                    76536 non-null  object
 17  all_facilities                       76536 non-null  object
 18  link                                 76536 non-null  object
 19  room_price_dict                      76536 non-null  object
 20  facilities_count                     76536 non-null  int64
 21  air conditioning                     76536 non-null  int64
 22  non-smoking rooms                    76536 non-null  int64
 23  fire extinguishers                   76536 non-null  int64
 24  cctv in common areas                 76536 non-null  int64
 25  private bathroom                     76536 non-null  int64
 26  smoke alarms                         76536 non-null  int64
 27  toilet                               76536 non-null  int64
 28  tv                                   76536 non-null  int64
 29  24-hour security                     76536 non-null  int64
 30  towels                               76536 non-null  int64
 31  free toiletries                      76536 non-null  int64
 32  24-hour front desk                   76536 non-null  int64
 33  shower                               76536 non-null  int64
 34  toilet paper                         76536 non-null  int64
 35  airport shuttle                      76536 non-null  int64
 36  elevator                             76536 non-null  int64
 37  linens                               76536 non-null  int64
 38  security alarm                       76536 non-null  int64
 39  flat-screen tv                       76536 non-null  int64
 40  daily housekeeping                   76536 non-null  int64
 41  cctv outside property                76536 non-null  int64
 42  room service                         76536 non-null  int64
 43  designated smoking area              76536 non-null  int64
 44  safe                                 76536 non-null  int64
 45  desk                                 76536 non-null  int64
 46  bidet                                76536 non-null  int64
 47  smoke-free property                  76536 non-null  int64
 48  baggage storage                      76536 non-null  int64
 49  cable channels                       76536 non-null  int64
 50  telephone                            76536 non-null  int64
 51  restaurant                           76536 non-null  int64
 52  key card access                      76536 non-null  int64
 53  electric kettle                      76536 non-null  int64
 54  meeting/banquet facilities           76536 non-null  int64
 55  laundry                              76536 non-null  int64
 56  fax/photocopying                     76536 non-null  int64
 57  upper floors accessible by elevator  76536 non-null  int64
 58  family rooms                         76536 non-null  int64
 59  wake-up service                      76536 non-null  int64
 60  concierge                            76536 non-null  int64
 61  hairdryer                            76536 non-null  int64
 62  slippers                             76536 non-null  int64
 63  key access                           76536 non-null  int64
 64  accessible parking                   76536 non-null  int64
 65  facilities for disabled guests       76536 non-null  int64
 66  wardrobe or closet                   76536 non-null  int64
 67  clothes rack                         76536 non-null  int64
 68  socket near the bed                  76536 non-null  int64
 69  bar                                  76536 non-null  int64
 70  ironing service                      76536 non-null  int64
 71  name                                 76536 non-null  object
 72  room_type_y                          76536 non-null  object
 73  nights_stayed                        76536 non-null  object
 74  month_stayed                         76536 non-null  object
 75  occupant_type                        76536 non-null  object
 76  from_country                         76536 non-null  object
 77  review_score                         76536 non-null  object
 78  date_reviewed                        76536 non-null  object
 79  short_review                         76536 non-null  object
 80  positive_review                      76536 non-null  object
 81  negative_review                      76536 non-null  object
dtypes: float64(1), int64(52), object(29)
memory usage: 48.5+ MB

In [7]:
print("Unique hotel names in hotel data: " + str(hotels['hotel_name_'].nunique()))
print("Unique hotel names in combined data: " + str(all['hotel_name_'].nunique()))
print("\n")
print("Unique links in reviews data: " + str(reviews['link'].nunique()))
print("Unique links in hotels data: " + str(hotels['link'].nunique()))
print("Unique links in combined data: " + str(all['link'].nunique()))
print("\n")
print(reviews.shape)
print(hotels.shape)
print(all.shape)

Unique hotel names in hotel data: 307
Unique hotel names in combined data: 307


Unique links in reviews data: 307
Unique links in hotels data: 307
Unique links in combined data: 307


(76536, 12)
(307, 71)
(76536, 82)

In [8]:
## save to pickle file
pickle.dump(all, open('../data/merged_hotel_data.pkl', "wb"))